spring.application.name=PiaCart
spring.datasource.url=jdbc:postgresql://db.vlkakbrwiytmqvmfmjkw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=@Anipia162405
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=900000